### ISSUE TITLE
Compile issue with Gettext 0.14.0

### ISSUE THREAD

**Issue by isaiahdw** [riverrun/not_qwerty123#9]
Anyone else having issues compiling with the latest Gettext version? I'm getting the following error:

```
== Compilation error in file lib/not_qwerty123/password_strength.ex ==
** (ArgumentError) *gettext macros expect translation keys (msgid and msgid_plural) and
domains to expand to strings at compile-time, but the given msgid
doesn't.

Dynamic translations should be avoided as they limit gettext's
ability to extract translations from your source code. If you are
sure you need dynamic lookup, you can use the functions in the Gettext
module:

    string = "hello world"
    Gettext.gettext(NotQwerty123.Gettext, string)

    (gettext) lib/gettext/compiler.ex:213: Gettext.Compiler.expand_to_binary/4
    expanding macro: NotQwerty123.Gettext.dgettext_noop/2
    lib/not_qwerty123/password_strength.ex:56: NotQwerty123.PasswordStrength.strong_password?/2
    expanding macro: NotQwerty123.Gettext.dgettext/3
    lib/not_qwerty123/password_strength.ex:56: NotQwerty123.PasswordStrength.strong_password?/2
    expanding macro: NotQwerty123.Gettext.gettext/2
    lib/not_qwerty123/password_strength.ex:56: NotQwerty123.PasswordStrength.strong_password?/2
    (elixir) expanding macro: Kernel.if/2
```

**Comment by Betree** [comment]
I had this issue with an old version (0.11.x I think ?) but updating to Gettext **0.13.1** fixed it for me.
A lot of libraries are impacted by this, for example ex_admin (see https://github.com/smpallen99/ex_admin/issues/425).

It happens when gettext is presented with strings concatenations like `text gettext "toTranslate" <> " "`. Gettext build translations at compile time and for some reasons it fails to recognize this as a valid string.

Try `0.13.1` and if you want to fix it on the library I'm sure @riverrun would like a PR 😉 It's a matter of converting translations like:

```elixir
markup do
    text gettext "Displaying" <> " "
end
```

To:

```elixir
markup do
    text (gettext "Displaying") <> " "
end
```

**Comment by riverrun** [comment]
Great! Thanks for the useful info.

**Comment by riverrun** [comment]
Just pushed version 2.3, with a fix (I hope), to hex.

Could you try it out and let me know if it works?

**Comment by isaiahdw** [comment]
@riverrun, I can confirm 2.3 fixes the issue. Thanks for pushing an update so quickly!

I don't see the changes on github, but feel free to close this issue. 😃

**Comment by riverrun** [comment]
I'll update master today - great to hear that fixed the issue
